In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Electronic_sales_Sep2023-Sep2024.csv")

# предпочитаемый метод оплаты

In [5]:
df[['Customer ID', 'Payment Method']].head(10)

   Customer ID Payment Method
0         1000    Credit Card
1         1000         Paypal
2         1002    Credit Card
3         1002           Cash
4         1003           Cash
5         1004    Credit Card
6         1005         Paypal
7         1005     Debit Card
8         1006     Debit Card
9         1006           Cash

df.group

# общие траты

In [7]:
df[['Customer ID', 'Total Price']].groupby('Customer ID').agg('sum')

             Total Price
Customer ID
1000             6279.42
1002             5020.60
1003               41.50
1004               83.00
1005            11779.11
...                  ...
19994            5504.87
19995            5394.56
19996           27296.78
19997            2528.26
19998             674.32

[12136 rows x 1 columns]

# количество денег, потраченных на дополнительные услуги и аксессуары

In [11]:
df[['Customer ID', 'Add-on Total']].groupby('Customer ID').agg('sum')

             Add-on Total
Customer ID
1000                66.30
1002                60.16
1003                35.56
1004                65.78
1005                75.33
...                   ...
19994               93.17
19995                0.00
19996              432.12
19997              101.34
19998                0.00

[12136 rows x 1 columns]

In [4]:
df.head(5)

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56